
vim.cmd('set nocompatible')
vim.cmd('set encoding=UTF-8')
vim.cmd('set tabstop=4')
vim.cmd('set shiftwidth=4')
vim.cmd('set autoindent')
vim.cmd('set smartindent')
vim.cmd('set number')
vim.cmd('set relativenumber')
vim.cmd('set mouse=a')
vim.cmd('set hlsearch')
vim.cmd('set incsearch')
vim.cmd('set hidden')
vim.cmd('set fdm=indent')
vim.cmd('set foldlevelstart=99')
vim.cmd('set ignorecase')
vim.cmd('set smartcase')
vim.cmd('set splitbelow')
vim.cmd('set splitright')
vim.cmd('set completeopt-=preview')

