plugin {
    hyprscrolling {
        column_width = 0.7
        explicit_column_widths = 0.5,0.7,1.0
        fullscreen_on_one_column = false
        focus_fit_method = 1
    }
}

source = ./monitors.conf
source = ./applications.conf
source = ./decorations.conf
source = ./animations.conf
source = ./input.conf
source = ./keybindings.conf
source = ./layout.conf
source = ./rules.conf
source = ./startup.conf
source = ./variables.conf
# source = ./plugins.conf


exec = notify-send "Hyprland Config Reload"
