source = ./monitors.conf
source = ./applications.conf
source = ./decorations.conf
source = ./animations.conf
source = ./input.conf
source = ./keybindings.conf
source = ./layout.conf
source = ./rules.conf
source = ./startup.conf
source = ./variables.conf
# source = ./plugins.conf

plugin {
    hyprscrolling {
        column_width = 0.7
        fullscreen_on_one_column = false
    }
}

exec = notify-send "Hyprland Config Reload"
