# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*,suppress_event maximize

# # Waybar
windowrule = match:class ^(Waybar)$, float true

# Matplotlib floating windows
windowrule = match:class ^(python3)$, float true

# Bluetooth manager
windowrule = match:class ^(blueberry.py)$, float true, size 640 480

# Network manager
windowrule = match:class ^(nm-connection-editor)$, float true, size 640 480

# Workspaces Bindings
windowrule = match:class ^(firefox)$, workspace 1
windowrule = match:class ^(zen)$, workspace 1
windowrule = match:class ^(org.pwmt.zathura)$, workspace 2
windowrule = match:class ^(mpv)$, workspace 2
windowrule = match:class ^(spotify)$, workspace 3

windowrule = match:class ^(dev.zed.Zed)$, workspace 7
windowrule = match:class ^(code)$, workspace 7
windowrule = match:class ^(kitty)$, workspace 8
windowrule = match:class ^(obsidian)$, workspace 9
windowrule = match:class ^(Notion)$, workspace 10

