env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = GDK_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland sioyek

permission = /usr/bin/hyprpm, plugin, allow

xwayland {
    enabled = true,
    use_nearest_neighbor = true,
}

